### ISSUE TITLE
Wrong Providers in the "Providers" tab

### ISSUE THREAD

**Issue by joaandrade** [NextGeoss/bug-tracking#4]
- [X] Bug
- [ ] Feature request

Use [X] to mark bug or feature

### Site URL:
https://catalogue.nextgeoss.eu/provider

### What steps can be taken to reproduce the issue? (Attach screenshots if available)
1) Access to https://catalogue.nextgeoss.eu
2) Insert NextGEOSS credentials
3) Click the tab "Providers"

### Please describe the actual behaviour (Attach screenshots if available)
Providers found:
- CMEMS
- GOME-2
- Sentinel)

### Please describe the expected behaviour
Providers should be:
- CMEMS
- WDC DLR instead of GOME-2
- ESA SciHub (for Sentinel)
- NOA (for Sentinel)
- CODE-DE (for Sentinel)

**Comment by michellecbox** [comment]
@joaandrade Here's some feedback from the team as to why we have this behaviour:

The unusual nature of the Sentinel datasets came from what Deimos coded up in their original Sentinel harvester. 
Every dataset belongs to either one and only one Provider. 
Or it doesn’t belong to any Provider at all. 
When a harvester harvests a dataset, it has to either associate it with a Provider or with no Provider at all. The choice is either to create three identical datasets, each associated with a different Provider
 Or one dataset associated with a single Provider and have its resources point to the three different sources. 
Deimos themselves chose the second option. 

Let me know if you have any questions.

**Comment by joaandrade** [comment]
@michellecbox in fact we do not have datasets with no Provider. 

We have datasets that belong to a single provider and, for the Sentinel data, sometimes a dataset belongs to more than one provider.

So the idea in the providers tab is to have the providers and inside the respective datasets, e.g.:

- Arctic Ocean Observed Sea Ice Concentration dataset - Provider is CMEMS
- Gome2 data (e.g. MetOP-A GOME-2 Ozone) - Provider is WDC DLR
- Sentinel-1 GRD dataset - It can belong to a single provider (e.g. SciHub, CODE-DE or NOA) or to belong to more than one provider (e.g. SciHub and CODE-DE)

If this last one is a problem, lets include the dataset in the SciHub Provider.

**Comment by michellecbox** [comment]
Ok, we have added this to our Backlog list as a new Feature

**Comment by michellecbox** [comment]
hi @koushikpanda152 we are having our next sprint planning on monday, I'll keep you posted after that. Is this considered a high priority for you?

**Comment by koushikpanda152** [comment]
Hi @michellecbox Thank you for the update.I think we should be okay if it is ready by the end of August before the RP-1. Hope that helps.

**Comment by koushikpanda152** [comment]
Hi @michellecbox I was wondering about any update about this issue, I could not see the changes in the portal.

**Comment by michellecbox** [comment]
Hi @koushikpanda152 we have not included this in our Sprint yet, but I have it on the backlog to work on it before the end of the month. I will let you know once completed.

**Comment by kmbn** [comment]
The names of the providers have been updated and logos have been added. Since a dataset cannot belong to more than one provider, the Sentinel datasets all belong to the ESA SciHub provider.
