### ISSUE TITLE
OpenSearch opened in the Production instance

### ISSUE THREAD

**Issue by joaandrade** [NextGeoss/bug-tracking#5]
- [ ] Bug
- [X] Feature request

Use [X] to mark bug or feature

### Site URL:
https://catalogue.nextgeoss.eu/opensearch/search.atom?

### What steps can be taken to reproduce the issue? (Attach screenshots if available)
Access the OpenSearch interface through https://catalogue.nextgeoss.eu/opensearch/search.atom?

### Please describe the actual behaviour (Attach screenshots if available)
Server Error message is displayed

### Please describe the expected behaviour
The OpenSearch XML answer should appear whether the user is logged in or not

**Comment by joaandrade** [comment]
@michellecbox I'm trying to access the OpenSearch in this instance and the "Server Error" remains.

Cheers,
João

**Comment by michellecbox** [comment]
@joaandrade I was able to reproduce the issue. The team will take a look.

**Comment by michellecbox** [comment]
issue fixed, closing it
@joaandrade can you re test?

**Comment by joaandrade** [comment]
It's working @michellecbox
